### ISSUE TITLE
PageVxxPxxx tags usually denote page endings, not page beginnings

### ISSUE THREAD

**Issue by pverkind** [OpenITI/oitei#4]
Currently, PageVxxPxxx tags are converted to <pb> tags, but PageVxxPxxx tags usually refer to the end of a page rather than the beginning of one. 

Does TEI have a way to encode page endings?

If not, `oimdp` should probably include a function to switch page numbers to the beginning of the page, something like:

```
header, body = re.split("#META#Header#End#", text)
header += "#META#Header#End#"
repaginated = ""
page_content = ""
for i, page in enumerate(re.split("(PageV[^P]+P\d+[AB]?)", body)):
    if i == 0 and page.strip() == "":
        # book starts with page numbers, so page numbers probably refer to the page beginning
        repaginated = body
        break
    if not page.startswith("PageV"):
        page_content = page
    else:
        # switch order of page number and page content:
        repaginated += page + page_content
```

**Comment by raffazizzi** [comment]
Hi @pverkind can you help me understand this better? I think that the page number wouldn't change whether the tag is positioned at the beginning of at the end of a page: page 1 is always page 1. For example I would expect the following examples to be equivalent?

```
==Start of page 1==

Text of page 1

==Start of page 2==

Text of page 2
```

```
Text of page 1

==End of page 1==

Text of page 2

==End of page 2==
```

I think what is of value here is the page number as opposed to its position. TEI only encodes page beginnings and semantically speaking there is only one page to encode, regardless of where the tag is placed. 

If it's an issue of where the page number is placed on the original page, that's a formatting rather than a semantic issue and it can be handled with attributes.

**Comment by raffazizzi** [comment]
Oh I get it now! The position of the tag needs to be moved in the TEI to be semantically correct. I would prefer to solve this in `oitei` since it's a specific quirk of TEI encoding as opposed to a mARkdown parsing issue.
